CREATE TABLE UserSessionEntity ( userId TEXT NOT NULL PRIMARY KEY, email TEXT NOT NULL, displayName TEXT NOT NULL, isGuest INTEGER NOT NULL DEFAULT 0, activePathId TEXT, createdAt TEXT NOT NULL );
CREATE TABLE LifePathEntity ( id TEXT NOT NULL PRIMARY KEY, name TEXT NOT NULL, description TEXT, isActive INTEGER NOT NULL DEFAULT 0 );
CREATE TABLE PrincipleEntity ( id TEXT NOT NULL PRIMARY KEY, lifePathId TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, FOREIGN KEY (lifePathId) REFERENCES LifePathEntity(id) ON DELETE CASCADE );
CREATE TABLE TemplateEntity ( id TEXT NOT NULL PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, taskCount INTEGER NOT NULL DEFAULT 5, frequency TEXT NOT NULL DEFAULT 'Daily', author TEXT, isCommunity INTEGER NOT NULL DEFAULT 0, isBookmarked INTEGER NOT NULL DEFAULT 0, isCustom INTEGER NOT NULL DEFAULT 0 );
CREATE TABLE TemplateHabitEntity ( id TEXT NOT NULL PRIMARY KEY, templateId TEXT NOT NULL, name TEXT NOT NULL, startTime TEXT NOT NULL, durationMinutes INTEGER NOT NULL, trackingMode TEXT NOT NULL, target TEXT NOT NULL, repeatDays TEXT NOT NULL, reminderEnabled INTEGER NOT NULL DEFAULT 1, sortOrder INTEGER NOT NULL, FOREIGN KEY (templateId) REFERENCES TemplateEntity(id) ON DELETE CASCADE );
CREATE TABLE UserTemplateEntity ( id TEXT NOT NULL PRIMARY KEY, userId TEXT NOT NULL, templateId TEXT NOT NULL, currentDay INTEGER NOT NULL DEFAULT 1, totalDays INTEGER NOT NULL DEFAULT 30, progressPercent INTEGER NOT NULL DEFAULT 0, isActive INTEGER NOT NULL DEFAULT 1, FOREIGN KEY (templateId) REFERENCES TemplateEntity(id) ON DELETE CASCADE );
CREATE TABLE PracticeEntity ( id TEXT NOT NULL PRIMARY KEY, principleId TEXT, title TEXT NOT NULL, targetDurationMinutes INTEGER NOT NULL, minimumDurationMinutes INTEGER NOT NULL, preferredTime TEXT, trackingMode TEXT NOT NULL, isActive INTEGER NOT NULL DEFAULT 1, FOREIGN KEY (principleId) REFERENCES PrincipleEntity(id) ON DELETE SET NULL );
CREATE TABLE ActionRecordEntity ( id TEXT NOT NULL PRIMARY KEY, practiceId TEXT NOT NULL, date TEXT NOT NULL, scheduledTime TEXT, status TEXT NOT NULL, completedAt TEXT, durationMinutes INTEGER, FOREIGN KEY (practiceId) REFERENCES PracticeEntity(id) ON DELETE CASCADE );
CREATE TABLE EvidenceEntity ( id TEXT NOT NULL PRIMARY KEY, actionRecordId TEXT NOT NULL, reflectionRating TEXT, note TEXT, mediaPath TEXT, createdAt TEXT NOT NULL, FOREIGN KEY (actionRecordId) REFERENCES ActionRecordEntity(id) ON DELETE CASCADE );
CREATE TABLE BookIdeaEntity ( id TEXT NOT NULL PRIMARY KEY, bookTitle TEXT NOT NULL, author TEXT NOT NULL, idea TEXT NOT NULL, practicalApplication TEXT NOT NULL, isExperimentActive INTEGER NOT NULL DEFAULT 0, experimentDaysLeft INTEGER, createdAt TEXT NOT NULL );
CREATE TABLE PatternInsightEntity ( id TEXT NOT NULL PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, recommendation TEXT NOT NULL, isApplied INTEGER NOT NULL DEFAULT 0, createdAt TEXT NOT NULL );
CREATE INDEX idx_action_date ON ActionRecordEntity(date);
CREATE INDEX idx_action_practice ON ActionRecordEntity(practiceId);
CREATE INDEX idx_practice_active ON PracticeEntity(isActive);
CREATE INDEX idx_principle_path ON PrincipleEntity(lifePathId);
CREATE INDEX idx_evidence_record ON EvidenceEntity(actionRecordId);
CREATE INDEX idx_template_community ON TemplateEntity(isCommunity);
CREATE INDEX idx_template_habit_tid ON TemplateHabitEntity(templateId);
CREATE INDEX idx_user_template_user ON UserTemplateEntity(userId);
